before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -s -w -X main.version={{.Summary}} -X main.commit={{.ShortCommit}} -X main.buildTimestamp={{ .Date }}
archives:
  - replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip      
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
