// Code generated by "stringer -type=kind -trimprefix=kind -output=enums_stringer.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[kindPlain-0]
	_ = x[kindGzip-1]
	_ = x[kindBzip2-2]
}

const _kind_name = "PlainGzipBzip2"

var _kind_index = [...]uint8{0, 5, 9, 14}

func (i kind) String() string {
	if i < 0 || i >= kind(len(_kind_index)-1) {
		return "kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _kind_name[_kind_index[i]:_kind_index[i+1]]
}
